# Generated by Django 6.0.7 on 2026-09-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representatives', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REPRESENTATIVE', 'Representative'), ('DIRECTORATE_STAFF', 'Directorate Staff'), ('UNIT_STAFF', 'Unit Staff'), ('COORDINATOR', 'Coordinator'), ('DIRECTOR', 'Director')], max_length=25),
        ),
    ]
