# Generated by Django 6.0.7 on 2026-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_user_unit_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('REPRESENTATIVE', 'Representative'), ('DIRECTORATE_STAFF', 'Directorate Staff'), ('UNIT_STAFF', 'Unit Staff'), ('COORDINATOR', 'Coordinator'), ('DIRECTOR', 'Director')], max_length=25),
        ),
    ]
