# Generated by Django 6.0.7 on 2026-09-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_requests', to='core.organization'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_requests', to='core.unit'),
        ),
    ]
